### ISSUE TITLE
Image blocks doesn't show image

### ISSUE THREAD

**Issue by danieljwestman** [dimitrov-adrian/directus-extension-editorjs-interface#1]
Image blocks doesn't show image. 

`{"errors":[{"message":"You're not allowed to read item \"5543bca3-5b56-46c9-8607-00b4af72ed0c\" in collection \"directus_files\".","extensions":{"collection":"directus_files","item":"5543bca3-5b56-46c9-8607-00b4af72ed0c","action":"read","stack":"Error: You're not allowed to read item \"5543bca3-5b56-46c9-8607-00b4af72ed0c\" in collection \"directus_files\".\n    at AuthorizationService.<anonymous> (/api/src/services/authorization.ts:412:10)\n    at Generator.throw (<anonymous>)\n    at rejected (/api/src/services/authorization.ts:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","code":"FORBIDDEN"}}]}`

You will need to pass a token, right?

**Comment by dimitrov-adrian** [comment]
Yes, the issue was in missing access token. It should be fixed with latest change.
