### ISSUE TITLE
Extension needs updating for rc.75+ (Vue 3)

### ISSUE THREAD

**Issue by benosman** [dimitrov-adrian/directus-extension-editorjs-interface#12]
I got caught by surprise, when updating directus to fix some issues I was experiencing, that this extension stopped working.

It turns out that it needs to be updated to Vue 3.

https://github.com/directus/directus/releases/tag/v9.0.0-rc.75

I had a quick look myself but so far haven't got a working rollup config.

**Comment by dimitrov-adrian** [comment]
Yes indeed, I had made a quick try but it seems there is upcoming changes in directus upstream, so I am thinking to wait their merge and then refactor against Vue 3

**Comment by nkCreation** [comment]
Hi, did you planned to fix this extensions ? or maybe you know what to do but don't have the time ? 
Thank's :)

**Comment by dimitrov-adrian** [comment]
It's now working with latest RC. Thanks!

**Comment by nkCreation** [comment]
You rocks !

**Comment by definiteIymaybe** [comment]
Awesome. Thanks a lot!
