### ISSUE TITLE
Install and use the interface

### ISSUE THREAD

**Issue by danieljwestman** [dimitrov-adrian/directus-extension-editorjs-interface#16]
Nice to test out editor.js in Directus 👍🏻

However, I can't get it to work on my Directus instance (v9.0.0-rc.95)...

1. Downloaded a copy of your repo
2. Run `npm install` in the editorjs dir
3. Run `npx directus-extension build`
4. Moved the index.js file to extensions/interfaces/editorjs
5. Started up Directus, `npm run dev`
6. My other extensions are loaded properly, but editorjs doesn't seem to be loaded
7. Created a new JSON field, but editorjs (Blocks) isn't an interface option, no where to be found...

**Comment by dimitrov-adrian** [comment]
I had tried exact same steps and it works.

Do you see it loaded in `Loaded extensions:` when starting Directus?

What is your setup, npm installation (version) or with docker?

**Comment by danieljwestman** [comment]
@dimitrov-adrian 
`Loaded extensions:` only includes my other extensions, not editorjs

I'm running a Directus clone locally.

**Comment by dimitrov-adrian** [comment]
It's funny, but in local build of directus I do not get `Loaded extensions:` in console. Anyway, tried to install on latest from main, and it seems to works, but needed to restart directus few times.

**Comment by danieljwestman** [comment]
Okay, weird. Testing with fresh Directus install and fresh download of editorjs extension with no luck...

**Comment by dimitrov-adrian** [comment]
What is your nodejs version, and what os?

**Comment by danieljwestman** [comment]
v.16.0.0
MacOS Catalina / Big Sur

**Comment by dandamian** [comment]
Clearing the browser cache helped in my case.

**Comment by dimitrov-adrian** [comment]
Still cannot reproduce.

npm package works for me, also using the https://github.com/dimitrov-adrian/directus-extension-editorjs-interface/releases/download/v1.0.1/index.js (from releases downloads) and putting into extensions/interfaces/editorjs/index.js works too.

**Comment by danieljwestman** [comment]
@dimitrov-adrian Okay...

I managed to install the extension with `npm install directus-extension-editorjs` and the it gets loaded when starting up. But how do I add the interface to a field? I can't find it...

![Skärmavbild 2021-11-29 kl  15 05 18](https://user-images.githubusercontent.com/20950568/143882055-8d79f9ef-0a7d-4d9f-8339-01278f592a9f.png)

![Screenshot of Start Page](https://user-images.githubusercontent.com/20950568/143882236-1342b16d-bb10-4052-a10d-0e72cafe608f.jpg)

![Screenshot of Start Page (1)](https://user-images.githubusercontent.com/20950568/143882215-d4e62eb6-f4aa-4dae-9785-8f71784c5c0c.jpg)

**Comment by danieljwestman** [comment]
Am I missing something @dimitrov-adrian ?

**Comment by dimitrov-adrian** [comment]
Actually no, I am trying to reproduce. Tried on Directus from docker and with local npm install, and on different browsers (Chrome, Safari and Firefox) but none of this make me missing the interface. I am out of ideas.

**Comment by danieljwestman** [comment]
You are using the old field creation flow? Could you attach an screendump?



tors 2 dec. 2021 kl. 19:19 skrev Adrian Dimitrov ***@***.***>:

**Comment by dimitrov-adrian** [comment]
https://user-images.githubusercontent.com/1009639/144491141-5b598aea-fd1a-403a-ab30-3b7e98ffbe38.mp4

Yes, in advanced field flow

**Comment by dimitrov-adrian** [comment]
Just added it to the new field flow (with 1.0.2)

**Comment by danieljwestman** [comment]
Thank you very much.

Suddenly it works for me too (with 1.0.2) 😅

Have a nice weekend!
