### ISSUE TITLE
Some Tools are missing from editor

### ISSUE THREAD

**Issue by madc** [dimitrov-adrian/directus-extension-editorjs-interface#18]
I just installed this interface via yarn with `latest` into the current version of Directus and it seems some tools (i.e. `embed`) do not appear, even if activated in the interface settings.

![image](https://user-images.githubusercontent.com/343392/136014804-5e89cc25-f088-47be-92ba-4e2f6e9f9f20.png)
![image](https://user-images.githubusercontent.com/343392/136014850-3f392623-31cc-4cc3-a5f3-75a27a9d0967.png)

**Comment by dimitrov-adrian** [comment]
Embed tool is an inline plugin, it acts upon link paste (like twitter, yt or facebook), some of the tools are for inline elements (when mark a text for example).

Thinking, may be the title "Toolbar" is bit confusing in such case.

**Comment by madc** [comment]
Thanks for taking the time to answer, really appreciate this. Coming from Directus I'm looking into Editor.js for the first time.
I read the plugins documentation before and  guess I expected it to work similar to the image plugin.

I'm having a hard time to understand this part of the docs: https://github.com/editor-js/embed#inline-toolbar
Do you think it would allow to add a button to the toolbox?

**Comment by dimitrov-adrian** [comment]
Not exactly, the inlineToolbar flags in the configuration enables the inline toolbar when marking a text, and in the case of embed tool, it applies to the input field after embeded content. The editorjs docs here are bit tricky to get in first glance.

**Comment by madc** [comment]
OK, thanks for the clarification. Everything works as intended so I'll close this.
