### ISSUE TITLE
Problem with adding a link

### ISSUE THREAD

**Issue by danieljwestman** [dimitrov-adrian/directus-extension-editorjs-interface#2]
Seems to be a styling problem with the link tool.

When selecting a string to link, the link url is the same color as the background:

![Skärmavbild 2020-12-07 kl  15 44 18](https://user-images.githubusercontent.com/20950568/101364954-73e2cc00-38a3-11eb-8101-791c30d29f43.png)

**Comment by dimitrov-adrian** [comment]
Yes, was a styling issue. Thanks!
