### ISSUE TITLE
Stable Directus v9

### ISSUE THREAD

**Issue by danieljwestman** [dimitrov-adrian/directus-extension-editorjs-interface#20]
> This extension is in development and most probably will have file structure change when Directus 9 official releases. Meanwhile breaking changes are possible in anytime.

Now Directus v9 is released. Are you planning to maintain this extension and make it stable? As explained in my other open issue there is problems to get the extension running...

**Comment by danieljwestman** [comment]
Ping @dimitrov-adrian 

Any plans making this compatible with Directus v9. There are a few new things regarding interface extensions.

**Comment by dimitrov-adrian** [comment]
Yes, I have such plans during the coming weekend.

@danieljwestman sorry for the delay, it was busy weeks

**Comment by danieljwestman** [comment]
Nice!

**Comment by dimitrov-adrian** [comment]
Closing in favour of [v1.0.1](https://www.npmjs.com/package/directus-extension-editorjs)
