### ISSUE TITLE
Add Height and Width attribute on result

### ISSUE THREAD

**Issue by nkCreation** [dimitrov-adrian/directus-extension-editorjs-interface#21]
Hello :)

Thank you for your work on this interface, it's almost perfect.

Do you think it's possible to add the image's dimension (width and height) alongside the file size in the response object ?
I think it's here but I don't know the content of `file` object. I'll give it a try today.

https://github.com/dimitrov-adrian/directus-extension-editorjs-interface/blob/8c225954f55ec86146f48d29f117bc288ce78ef3/src/custom-plugins/editorjs-uploader.js#L50-L56

Thank you !

**Comment by dimitrov-adrian** [comment]
Looks useful, thank you @nkCreation!

**Comment by dimitrov-adrian** [comment]
It's on 1.1.0 already.
