### ISSUE TITLE
How to load the extension into system?

### ISSUE THREAD

**Issue by jocstech** [dimitrov-adrian/directus-extension-editorjs-interface#3]
Hello, Sorry, but how do I load the extension into system? I did copy the dist file into interfaces/index.js and reload the Directus instance, but nothing is there.... is there any special instruction I need do?

**Comment by jocstech** [comment]
I found the correct way to install the EditorJS extension by asking the author:

1, Firstly, copy the ```index.js``` file from ```/dist``` folder to your Directus project path: ```/extensions/interfaces/editorjs/index.js```
2, Reload your Directus server instance 
3, When you create the text editor field please select ```JSON``` field type instead of text, select ```Block Editor``` for the interface property, finally select raw value for the display property. 
4, Done!

**Comment by dimitrov-adrian** [comment]
Yes, it need own directory.

When Directus 9 releases, will include more friendly documentation about it and how to install and will build more proper package.
