### ISSUE TITLE
[Freelancer] medic appointement for direcuts v9.

### ISSUE THREAD

**Issue by hermesalvesbr** [dimitrov-adrian/directus-extension-editorjs-interface#33]
Hi

I'm looking for a custom extension for medic appointement for direcuts v9. 

**Features**
1 Select the doctor (load the avaliable dates)
2 Show by color in the date picker the avaliable dates
3 Schedule an appointment choosing the free hours
4 Validate for date/hour conflicts.

**SAMPLE:**
![166241874-bd89e5ef-07c8-4fa4-84d7-a77ff18999c8](https://user-images.githubusercontent.com/379850/166673114-6f98733e-2dea-49df-9723-cc70b0bcc402.png)

Do you have avaliability for this freelancer?

**Comment by dimitrov-adrian** [comment]
This have nothing to do with the extension itself. I am closing this issue.

---
Off-topic there is different approaches to do the goal. I think the easiest and almost out of the box solution could be if you pre-regenerate the slots for some period of time ahead (also if it's really for medical time slots and hour booking) definitely collision will not be a nice to handle. So if you generate records ahead, you could use simply a flag that indicate if it's free or not, and future more you could use the calendar layout for nice display, as well as could benefit from the shareable forms.
