### ISSUE TITLE
EditorJS extension triggers a field update upon view

### ISSUE THREAD

**Issue by mark-james** [dimitrov-adrian/directus-extension-editorjs-interface#34]
Hi Adrian,
Great job on this extension.
When I got to a page with this extension, it triggers the need for an update when just viewing. On inspection, it's caused because EditorJS updates the 'time' variable within the JSON output.

{
    **"time" : 1550476186479,**
    "blocks" : [],
    "version" : "2.8.1"
}

Do you know of a way of disabling this behaviour?

Thanks
Mark

**Comment by bamboowonder** [comment]
confirmed this is happening for me as well on 9.12.2
and great extension btw.  thank you.

**Comment by dimitrov-adrian** [comment]
Yes, indeed. Sometimes the editorjs tends to trigger update even no real update of the content is happened, and it then touch the time only, which is itself is a value change for directus.

I'll try to find what causing this kind of touches.

**Comment by dimitrov-adrian** [comment]
Fixed in latest release
