### ISSUE TITLE
This content is blocked when use Youtube Embed

### ISSUE THREAD

**Issue by talpha14** [dimitrov-adrian/directus-extension-editorjs-interface#36]
Hello, 

I want to use Embed block, test on youtube embed and got error.

I tested Embed block on Editor.js website and no error

`This content is blocked. Contact the site owner to fix the issue.`

Thank you

**Comment by northen-mindset** [comment]
How did you solve the issue?
In my case setting the following environment variable for Directus helped:

```
CONTENT_SECURITY_POLICY_DIRECTIVES__CHILD_SRC: "https://www.youtube.com"
```
Reference: https://docs.directus.io/self-hosted/config-options.html#security
