### ISSUE TITLE
The EditorJS instance won't be loaded when you login with NON-admin account. 

### ISSUE THREAD

**Issue by jocstech** [dimitrov-adrian/directus-extension-editorjs-interface#4]
The EditorJS instance won't be loaded when you login with NON-admin account. 

The Editor works super fine with any admin accounts, however when you login to Directus CMS with a regular account like 'Editor', the editor itself won't be load correctly, and there is the console errors:

```
index.js:3 Editor.js is not ready because of Error: To enable read-only mode all connected tools should support it. Tools list don't support read-only mode.
TypeError: Cannot read property 'toggle' of undefined
index.js:3 Uncaught (in promise) Error: To enable read-only mode all connected tools should support it. Tools list don't support read-only mode.
```

any ideas?

**Comment by dimitrov-adrian** [comment]
It's fixed with latest changes. Thanks!
