### ISSUE TITLE
When "Border" option is unchecked in interface setting, the Editor turns read-only mode for NON-admin users.

### ISSUE THREAD

**Issue by jocstech** [dimitrov-adrian/directus-extension-editorjs-interface#5]
I found interesting bug:

When unchecked "Border" option in interface setting, the Editor turns read-only mode for NON-admin users.
If the Border option checked, everything works fine.

The output error is same as #4

**Comment by jocstech** [comment]
Updates:

I found there are some possible unstable issues before the '**Border**' issue,
When **non-admin** user flush out the login session (clear cache/cookies) and re-login again, the EditorJS shows up but it reminds read-only status ( uneditable ).

**Comment by dimitrov-adrian** [comment]
Yes, the issue was on the read-only mode. Fixed in 2f2ac89
