### ISSUE TITLE
Unable to save bold text in Paragraph block

### ISSUE THREAD

**Issue by thomasazar** [dimitrov-adrian/directus-extension-editorjs-interface#6]
When I enter text into a Paragraph block, the text is rendered as bold in the interface (the bold "B" is even selected when the text is highlighted). However, when it is saved, the accompanying `<b>` or `<strong>` tags are not saved with it. This happens even if un-bold and re-bold the text.

![Screenshot from 2021-02-12 11-42-00](https://user-images.githubusercontent.com/7015349/107795998-59a3ef00-6d27-11eb-87f6-5d94da2756b4.png)

![Screenshot from 2021-02-12 11-44-22](https://user-images.githubusercontent.com/7015349/107796305-b1425a80-6d27-11eb-980a-55ef1c1dc417.png)

**Comment by dimitrov-adrian** [comment]
I tried, but cannot reproduce on my own. What set of tools you have enabled in the interface configuration?

**Comment by thomasazar** [comment]
The problem seems to surface randomly — sometimes the bold tag is saved, sometimes it isn't. I'm currently on v9.0.0-rc37, using the Docker image. I've enabled the following 10 tools:

- Header
- List
- Paragraph
- Image
- Attaches
- Table
- Quote
- Underline
- Checklist

**Comment by thomasazar** [comment]
I decided to take a crack at figuring out what's going on, and here's what I came up with.

When I opened the Developer Tools within Firefox, I saw that the font on the Paragraph block was using a weight of 500. Changing that to 400 made the text of that block render "normal" — that is, without the faux bold. Then, if I did bold a selection of text, it was properly saved and recalled upon opening the item again.

To make this a permanent change, I inserted the following CSS in my Project Settings:

```
.ce-paragraph.cdx-block {
    font-weight: 400;
}
```

**Comment by dimitrov-adrian** [comment]
> I decided to take a crack at figuring out what's going on, and here's what I came up with.
> 
> When I opened the Developer Tools within Firefox, I saw that the font on the Paragraph block was using a weight of 500. Changing that to 400 made the text of that block render "normal" — that is, without the faux bold. Then, if I did bold a selection of text, it was properly saved and recalled upon opening the item again.
> 
> To make this a permanent change, I inserted the following CSS in my Project Settings:
> 
> ```
> .ce-paragraph.cdx-block {
>     font-weight: 400;
> }
> ```

I had added such reset, and with latest changes from editorjs, I cannot reproduce anymore.

**Comment by thomasazar** [comment]
Yup, looks like it's working on my end, too. Thank you for the update!
